pipeline {
    agent any
    parameters {
        choice ( name : 'mode' , choices: ['deploy', 'start', 'restart', 'stop'], description : 'select the deployment' )
        string ( name: 'Branch', defaultValue: 'main', description: 'git branch tag' )
    }

    stages {
        stage('clean the workspace') {
            steps {
                cleanWs()
            }
        }

        stage('clone the repository') {
            steps {
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: "${params.Branch}"]],
                    userRemoteConfigs: [[url: 'https://github.com/shinrah/JAVA-Application-.git']]
                ])
            }
        }

        stage('build the project') {
            steps {
                dir('JAVA-Application-') {
                    echo 'check the current java version'
                    sh 'java --version'
                    echo 'check the current maven version'
                    sh 'mvn -version'
                    echo 'check the pom.xml file availablily'
                    sh "ls -l 'pom.xml'"
                    sh 'mvn clean install'
                }
            }
        }

        stage('clean') {
            steps {
                cleanWs()
            }
        }
        
    }
}
