pipeline {
    agent any

    environment {
        giurl = 'https://github.com/shinrah/java-fix-1.git'
        gitBranch = "${params.GIT_Branch_Tag}"
        formattedGitBranch = "${params.GIT_Branch_Tag}" // Adjust if formatting is needed
    }

    parameters {
        choice(name: 'mode', choices: ['Deploy', 'stop', 'start', 'restart'], description: 'Choose mode for deployment or starting the application server')
        choice(name: 'host', choices: ['main', 'master', 'UAT'], description: 'Choose environment to deploy master')
        choice(name: 'GIT_Branch_Tag', choices: ['main', 'master', 'feature-branch', 'UAT'], description: 'Select Git branch to deploy')
    }

    stages {
        stage('git checkout') {
            steps {
                git credentialsId: 'github-token', branch: "${params.GIT_Branch_Tag}", url: "${giurl}"
            }
        }
    }
}

