pipeline {
    agent any

    stages {
        stage('clean the workspace') {
            steps {
                cleanWs()
            }
        }

        stage('clone the repository') {
            steps {
                sh 'git clone -b main https://github.com/shinrah/JAVA-Application-.git' 
            }
        }

        stage('build the project') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
