pipeline {
    agent any
    parameters {
        choice ( name : 'mode' , choices: ['deploy', 'start', 'restart', 'stop'], description : 'select the deployment' )
        string ( name: 'Branch', defaultValue: 'main', description: 'git branch tag' )
    }

    stages {
        stage('clean the workspace') {
            steps {
                cleanWs()
            }
        }

        stage('clone the repository') {
            steps {
                sh "git clone -b ${params.Branch} https://github.com/shinrah/JAVA-Application-.git"
            }
        }

        stage('build the project') {
            steps {
                dir('JAVA-Application-') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('clean') {
            steps {
                cleanWs()
            }
        }
        
    }
}
